### ISSUE TITLE
npm start fails with missing file "dist/rsvp.js"

### ISSUE THREAD

**Issue by tschneidereit** [eviltrout/ember-performance#38]
After following the steps in the README and working around the two issues I filed before. Full output:

```
npm start

> ember-performance-jjabrams@0.9.0 start /Users/till/mozilla/others/ember/perf
> ember server

version: 0.1.15
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
In bower directory bower_components/rsvp: Cannot find file specified in bower `main` property: dist/rsvp.js
Error: In bower directory bower_components/rsvp: Cannot find file specified in bower `main` property: dist/rsvp.js
    at MainFilePicker.write (/Users/till/mozilla/others/ember/perf/node_modules/broccoli-bower/index.js:35:13)
    at MainFilePicker.Writer.read (/Users/till/mozilla/others/ember/perf/node_modules/broccoli-bower/node_modules/broccoli-writer/index.js:11:31)
    at /Users/till/mozilla/others/ember/perf/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:79:23
    at $$$internal$$tryCatch (/Users/till/mozilla/others/ember/perf/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/till/mozilla/others/ember/perf/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at /Users/till/mozilla/others/ember/perf/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1096:13
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/till/mozilla/others/ember/perf/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by eviltrout** [comment]
Fixed in e782245 thanks.
