### ISSUE TITLE
Error on install in development mode 

### ISSUE THREAD

**Issue by OrKoN** [eviltrout/ember-performance#41]
I get an error:

```
Path or pattern "bootstrap.css" did not match any files
Error: Path or pattern "bootstrap.css" did not match any files
    at Object.multiGlob (/home/alex/ember-performance/node_modules/broccoli-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:203:13)
    at /home/alex/ember-performance/node_modules/broccoli-concat/index.js:62:32
    at $$$internal$$tryCatch (/home/alex/ember-performance/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/home/alex/ember-performance/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/home/alex/ember-performance/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at $$rsvp$asap$$flush (/home/alex/ember-performance/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at process._tickCallback (node.js:355:11)
```

```
node --version
v0.12.5
npm --version
2.8.4
bower --version
1.4.1
```

**Comment by GavinJoyce** [comment]
Bootstrap seems to expose `bootstrap.less`, not `bootstrap.css` in https://github.com/twbs/bootstrap/blob/master/bower.json#L18

**Comment by OrKoN** [comment]
@GavinJoyce Thanks for the tip!
